export default [
    { title: '弓箭手村', artist: ' ', src: 'bgm/1.mp3' },
    { title: '天空之城', artist: ' ', src: 'bgm/2.mp3' },
    { title: '水世界', artist: ' ', src: 'bgm/3.mp3' },
    { title: '水晶花園', artist: ' ', src: 'bgm/4.mp3' },
    { title: '冰原雪域', artist: ' ', src: 'bgm/5.mp3' },
    { title: '地球防衛總部', artist: ' ', src: 'bgm/6.mp3' },
    { title: '尖耳狐狸村', artist: ' ', src: 'bgm/7.mp3' },
    { title: '奇幻村', artist: ' ', src: 'bgm/8.mp3' },
    { title: '玩具城', artist: ' ', src: 'bgm/9.mp3' },
    { title: '勇士之村', artist: ' ', src: 'bgm/10.mp3' },
    { title: '耶雷弗', artist: ' ', src: 'bgm/11.mp3' },
    { title: '埃德爾斯坦', artist: ' ', src: 'bgm/12.mp3' },
    { title: '桃花仙境', artist: ' ', src: 'bgm/13.mp3' },
    { title: '神木村', artist: ' ', src: 'bgm/14.mp3' },
    { title: '納希綠洲城', artist: ' ', src: 'bgm/15.mp3' },
    { title: '童話村', artist: ' ', src: 'bgm/16.mp3' },
    { title: '瑞恩村', artist: ' ', src: 'bgm/17.mp3' },
    { title: '萬神殿', artist: ' ', src: 'bgm/18.mp3' },
    { title: '瑪迦提亞城', artist: ' ', src: 'bgm/19.mp3' },
    { title: '維多利亞港', artist: ' ', src: 'bgm/20.mp3' },
    { title: '赫力席母奪回總部', artist: ' ', src: 'bgm/21.mp3' },
    { title: '墮落城市', artist: ' ', src: 'bgm/22.mp3' },
    { title: '魔法森林', artist: ' ', src: 'bgm/23.mp3' },
    { title: '靈藥幻境', artist: ' ', src: 'bgm/24.mp3' },
    { title: '櫻花處', artist: ' ', src: 'bgm/25.mp3' },
]